# Generated by Django 5.1.4 on 2024-12-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=255)),
                ('descricao_tarefa', models.TextField(blank=True, null=True)),
                ('status_tarefa', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Finalizada', 'Finalizada')], default='Pendente', max_length=12, verbose_name='Status da tarefa')),
            ],
        ),
    ]
